#!/bin/bash

if [[ "$BLOCK_BUTTON" == "1" ]]; then
    chosen=$(printf " Shutdown\n Reboot\n Lock\n Logout" | rofi -dmenu -i -p "Power Menu")
    case "$chosen" in
        " Shutdown") systemctl poweroff ;;
        " Reboot") systemctl reboot ;;
        " Lock") i3lock ;;
        " Logout") i3-msg exit ;;
    esac
fi

echo ""

